// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import  'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_ZwgnGfdKfOZb1MZZXIKuODiTS-Ht2zM',
    appId: '1:414521075405:web:0a0cc4ea4f306ba86bab84',
    messagingSenderId: '414521075405',
    projectId: 'tadd-2c10d',
    authDomain: 'tadd-2c10d.firebaseapp.com',
    databaseURL: 'https://tadd-2c10d-default-rtdb.firebaseio.com',
    storageBucket: 'tadd-2c10d.appspot.com',
    measurementId: 'G-8PN7G8TGB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuFWWWK3klt76aon40zbITz37a4ehPXes',
    appId: '1:414521075405:android:94fafe6ddf0fc5876bab84',
    messagingSenderId: '414521075405',
    projectId: 'tadd-2c10d',
    databaseURL: 'https://tadd-2c10d-default-rtdb.firebaseio.com',
    storageBucket: 'tadd-2c10d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0KMBFMLujVAeBYF7DtOeiBZ-aTzFq-c8',
    appId: '1:414521075405:ios:0741778a01641d8c6bab84',
    messagingSenderId: '414521075405',
    projectId: 'tadd-2c10d',
    databaseURL: 'https://tadd-2c10d-default-rtdb.firebaseio.com',
    storageBucket: 'tadd-2c10d.appspot.com',
    iosClientId: '414521075405-bl4g6ku21q4djvfbi91qlbokclq88jmf.apps.googleusercontent.com',
    iosBundleId: 'com.example.melonguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0KMBFMLujVAeBYF7DtOeiBZ-aTzFq-c8',
    appId: '1:414521075405:ios:0741778a01641d8c6bab84',
    messagingSenderId: '414521075405',
    projectId: 'tadd-2c10d',
    databaseURL: 'https://tadd-2c10d-default-rtdb.firebaseio.com',
    storageBucket: 'tadd-2c10d.appspot.com',
    iosClientId: '414521075405-bl4g6ku21q4djvfbi91qlbokclq88jmf.apps.googleusercontent.com',
    iosBundleId: 'com.example.melonguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_ZwgnGfdKfOZb1MZZXIKuODiTS-Ht2zM',
    appId: '1:414521075405:web:90c94d41dff358306bab84',
    messagingSenderId: '414521075405',
    projectId: 'tadd-2c10d',
    authDomain: 'tadd-2c10d.firebaseapp.com',
    databaseURL: 'https://tadd-2c10d-default-rtdb.firebaseio.com',
    storageBucket: 'tadd-2c10d.appspot.com',
    measurementId: 'G-PW24M2XZ93',
  );
}
